### ISSUE TITLE
Specify a License

### ISSUE THREAD

**Issue by ticky** [phyber/ciso#1]
Currently, no license is specified, which makes dealing in modifications of this software impossible. I’d suggest [considering adding a license](https://choosealicense.com) so it’s clear how this is intended to be used and shared!c

**Comment by phyber** [comment]
Hi!

Sorry, thanks for pointing this out. I'll add a license to the code in a while, likely BSD-3-Clause or MIT.

**Comment by ticky** [comment]
Thank you!

**Comment by phyber** [comment]
BSD-3-Clause license is added, thanks again for the reminder. :+1:
